version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3

    steps:
      - checkout

      - restore_cache:
          keys:
            - gem-cache-v1-{{ checksum "Gemfile.lock" }}
            - gem-cache-v1-

      - run:
          name: Install dependencies
          command: |
            gem  update --system
            gem install bundler
            bundle install
      - save_cache:
          key: gem-cache-v1-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

workflows:
  version: 2
    build_and_test:
      jobs:
        - build


