
version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-node
     steps:
      - restore_cache:
          keys:
            - source-v1-{{ checksum "Gemfile.lock" }}
            - source-v1-

      - run: bundle install --path vendor/bundle

      - save_cache:
          key: source-v1-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

